### ISSUE TITLE
Erro "Request failed with status code 400"

### ISSUE THREAD

**Issue by AugustoResende** [heliojuniorkroger/tibo#1]
(node:22908) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 400
(node:22908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AugustoResende** [comment]
Status Code:429 Too Many Requests

**Comment by heliojuniorkroger** [comment]
Tinder's API self closes after a hard load of requests. You must wait for a while till you start using Tibo again...
